name: Delete old Releases and Workflows
on:
  workflow_dispatch:
    inputs:
      days:
        description: "Number of days."
        required: true
        default: "2"
      minimum_runs:
        description: "The minimum runs to keep for each workflow."
        required: true
        default: "2"
      delete_workflow_pattern:
        description: "The name or filename of the workflow. if not set then it will target all workflows."
        required: false
      delete_workflow_by_state_pattern:
        description: "Remove workflow by state: active, deleted, disabled_fork, disabled_inactivity, disabled_manually"
        required: true
        default: "All"
        type: choice
        options:
          - "All"
          - active
          - deleted
          - disabled_inactivity
          - disabled_manually
      delete_run_by_conclusion_pattern:
        description: "Remove workflow by conclusion: action_required, cancelled, failure, skipped, success"
        required: true
        default: "All"
        type: choice
        options:
          - "All"
          - action_required
          - cancelled
          - failure
          - skipped
          - success
      dry_run:
        description: "Only log actions, do not perform any delete operations."
        required: false
  schedule:
    - cron: '00 22 * * 0'

permissions: write-all

jobs:
  del_runs:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete old Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
          delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern }}
          delete_workflow_by_state_pattern: ${{ github.event.inputs.delete_workflow_by_state_pattern }}
          delete_run_by_conclusion_pattern: ${{ github.event.inputs.delete_run_by_conclusion_pattern }}
          dry_run: ${{ github.event.inputs.dry_run }}

      - name: Delete old Releases
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: 0
          delete_tags: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git identity
        run: |
          git config --global user.email "atimor@126.com" 
          git config --global user.name "liqideqq"

      - name: Delete all remote Git tags
        run: |
          echo "Fetching all tags..."
          git fetch --tags

          echo "Deleting all remote tags..."
          git tag -l | while read tag; do
            echo "Deleting tag: $tag"
            git push origin :refs/tags/$tag
          done
